from django.urls import path, include
from . views import *

urlpatterns = [
    path('verify-token/', TokenVerifyView.as_view()),
    path('register-user/', RegisterUserView.as_view()),
    path('get-suggested-slug-for-company/',
         SuggestedSlugCompanyView.as_view()),
    path('email-verify/', EmailVerifyView.as_view()),
    path('reset-password-link/', ResetPasswordEmailSendView.as_view()),
    path('reset-password/', ResetPasswordEmailResponseView.as_view()),
    path('register-company/', RegisterCompanyView.as_view()),
    path('update-user-profile/', UserProfileUpdateView.as_view()),
    path('create-user-contact/', UserContactCreateView.as_view()),
    path('update-user-contact/<int:pk>', UserContactUpdateView.as_view()),
    path('create-user-address/', UserAddressCreateView.as_view()),
    path('update-user-address/<int:pk>', UserAddressUpdateView.as_view()),
    path('create-user-gst/', UserGSTCreateView.as_view()),
    path('update-user-gst/<int:pk>', UserGSTUpdateView.as_view()),
    path('admin-login/', AdminLoginView.as_view()),
    path('get-staff-roles/', StaffRoleGetView.as_view()),
    path('get-order-status/', OrderStatusGetView.as_view()),
    path('create-category/', CategoryCreateView.as_view()),
    path('update-category/<int:pk>', CategoryUpdateView.as_view()),
    path('import-categories/', CategoriesImportView.as_view()),
    path('delete-category/', CategoryDeleteView.as_view()),
    path('get-categories/', CategoryGetView.as_view()),
    path('create-product/', ProductCreateView.as_view()),
    path('update-product/<int:pk>', ProductUpdateView.as_view()),
    path('import-products/', ProductsImportView.as_view()),
    path('create-coupon/', CouponCreateView.as_view()),
    path('update-coupon/<int:pk>', CouponUpdateView.as_view()),
    path('delete-coupon/', CouponDeleteView.as_view()),
    path('create-staff/', StaffCreateView.as_view()),
    path('delete-staff/', StaffDeleteView.as_view()),
    path('update-staff-role/<int:pk>', StaffRoleUpdateView.as_view()),
    path('staff-confirm-response/', StaffConfirmationEmailResponseView.as_view()),
    path('create-user-cart/', UserCartCreateView.as_view()),
    path('update-user-cart/<int:pk>', UserCartUpdateView.as_view()),
    path('delete-user-cart/', UserCartDeleteView.as_view()),
    path('create-order/', OrderCreateView.as_view()),
    path('update-order/<int:pk>', OrderUpdateView.as_view()),
    path('update-scanned-image/', ScannedImageCreateDeleteView.as_view()),
]
